---
# 项目启动端口
server:
  port: 8080

---
# 静态文件请求匹配方式
spring:
  mvc:
    static-path-pattern: /**

---
# 修改默认的静态寻址资源目录
spring:
  resources:
    static-locations: classpath:/static/,classpath:upload/,file:static/

---
# 数据库配置信息
spring:
  datasource:
    # 使用druid数据源  
    type: com.alibaba.druid.pool.DruidDataSource  
    # 数据库连接信息
    url: jdbc:sqlserver://111.1.186.226:1488;DatabaseName=hydee_WMScs
    username: sa
    password: hydee
    # 数据库连接驱动
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # 初始化大小，最小，最大
    initialSize: 20
    minIdle: 20
    maxActive: 100
    # 配置获取连接等待超时的时间(毫秒)
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接(毫秒)
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 100
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    logSlowSql: true
    # 开启Druid keepAlive 功能,防止数据库连接被防火墙主动关闭
    keepAlive: true
  jpa:
    database: sqlserver

---
# mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hydee.ydky.entity
  # 单次批处理插入最大执行数量配置(请不要随意扩大配置,导致服务器内存溢出)
  batch-commitcount: 2000

---
# 系统配置参数
server:
  api:
    sign:
      expired: 300
      enabled: false
      
---
# 配置分页插件pagehelper
pagehelper:
  helper-dialect: oracle
  auto-dialect: true
  reasonable: true
  params: count=countSql
  support-methods-arguments: true
